"""
train_aggregator.py
===================
Phase-1 STAGE-B aggregator: pillar scores -> overall PSA grade.

This does NOT touch Stage A (YOLO -> warp -> Claude still produces the per-pillar
scores). It only learns how to COMBINE the 4 pillar scores into one overall grade,
replacing Claude's `overall_score` with a tiny linear model whose coefficients can
run client-side (so adjusting boundaries re-grades instantly with no Claude call).

Trains a LinearRegression on df_psa_claude.pkl and emits:
  - grade_model.json                          (for any server-side use)
  - <extension>/grade_model.js                (window.GRADE_MODEL for the panel)

Usage:
  python train_aggregator.py [path/to/df.pkl] [path/to/extension/grade_model.js]
"""

import sys
import json
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_predict

PILLARS = ["centering_score", "corners_score", "edges_score", "surface_score"]

DF_PATH  = sys.argv[1] if len(sys.argv) > 1 else "df_psa_claude.pkl"
EXT_PATH = sys.argv[2] if len(sys.argv) > 2 else \
    "/Users/srinivasdoddi/srini/agentic-card-seller-os/extension/grade_model.js"


def load_clean(path):
    df = pd.read_pickle(path)
    for c in ["grade_actual", *PILLARS]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df.dropna(subset=["grade_actual", *PILLARS]).copy()
    if "error" in df:
        df = df[df["error"].isna() | (df["error"] == "")]
    if "truncated" in df:
        df = df[df["truncated"] != True]  # noqa: E712
    return df


def metrics(pred, y):
    pred = np.asarray(pred, float)
    return {
        "mae":     round(float(np.mean(np.abs(pred - y))), 4),
        "exact":   round(float(np.mean(np.round(pred) == y)), 4),
        "within1": round(float(np.mean(np.abs(np.round(pred) - y) <= 1)), 4),
    }


def main():
    df = load_clean(DF_PATH)
    X = df[PILLARS].values
    y = df["grade_actual"].values.astype(float)
    n = len(df)
    print(f"Training on {n} rows from {DF_PATH}")

    model = LinearRegression().fit(X, y)
    train_m = metrics(model.predict(X), y)
    cv_m    = metrics(cross_val_predict(model, X, y, cv=5), y) if n >= 10 else None

    weights = {
        "centering": round(float(model.coef_[0]), 6),
        "corners":   round(float(model.coef_[1]), 6),
        "edges":     round(float(model.coef_[2]), 6),
        "surface":   round(float(model.coef_[3]), 6),
    }
    payload = {
        "intercept": round(float(model.intercept_), 6),
        "weights":   weights,
        "n":         n,
        "train":     train_m,
        "cv":        cv_m,
        "features":  ["centering", "corners", "edges", "surface"],
        "note":      "Stage-B only: pillar scores -> overall PSA grade. "
                     "centering feature is the geometric centering score at inference.",
    }

    print("intercept:", payload["intercept"])
    print("weights  :", weights)
    print("train    :", train_m)
    print("cv (5fold):", cv_m)

    with open("grade_model.json", "w") as f:
        json.dump(payload, f, indent=2)
    print("wrote grade_model.json")

    js = (
        "// AUTO-GENERATED by grading_server/train_aggregator.py — do not edit by hand.\n"
        "// Stage-B aggregator: pillar scores -> overall PSA grade (no Claude call).\n"
        f"// Trained on {n} rows. CV MAE={cv_m['mae'] if cv_m else 'n/a'} "
        f"within1={cv_m['within1'] if cv_m else 'n/a'}.\n"
        f"window.GRADE_MODEL = {json.dumps(payload)};\n"
    )
    try:
        with open(EXT_PATH, "w") as f:
            f.write(js)
        print(f"wrote {EXT_PATH}")
    except OSError as e:
        print(f"WARNING: could not write extension model file: {e}")


if __name__ == "__main__":
    main()
